---
name: Container Image

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types:
    - published

jobs:
  # https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images
  container-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Push to Docker Hub
      # https://github.com/docker/build-push-action
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: karlkfi/using-kubernetes-the-hard-way
        tag_with_ref: true
        tag_with_sha: true
    - name: Cleanup Docker Config
      run: rm /github/home/.docker/config.json
